name: erikwebb dot net
pygments: true

author :
  name : Erik Webb
  headshot : /static/images/headshot_casual.jpg
  twitter : erikwebb
  linkedin : erikwebb
  github : erikwebb
  drupal : 273404
  slideshare : erikwebb
  feedname : erikwebbdotnet
  flickr : erikwebb
